spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
recipeapp:
  server:
    url: ${RECIPE_SERVER_URL}